import { Plan, Price } from '@/types'

export const pricing: Record<Price, Plan> = {
  3699: {
    name: 'Mensal',
    price: 3699,
    period: 'mês',
    benefitsIncluded: [
      '100% em nuvem',
      'Análises em tempo real',
      'Utilização ilimitada',
      'Histórico de apostas',
      'Suporte',
      'Crie sua Estratégia (em breve)',
      'Validador de Estratégias (em breve)',
    ],
    benefitsNotIncluded: ['Suporte individual', 'Estratégias Exclusivas'],
    isPopular: true,
    license: 'vip',
    recurrency: 'monthly',
  },
  6999: {
    name: 'Trimestral',
    period: 'trimestre',
    price: 6999,
    benefitsIncluded: [
      '100% em nuvem',
      'Análises em tempo real',
      'Utilização ilimitada',
      'Histórico de apostas',
      'Suporte Individual',
      'Crie sua Estratégia (em breve)',
      'Validador de Estratégias (em breve)',
    ],
    benefitsNotIncluded: ['Estratégias Exclusivas'],
    license: 'vip',
    recurrency: 'quarterly',
  },
  14900: {
    name: 'Anual',
    price: 14900,
    period: 'ano',
    benefitsIncluded: [
      '100% em nuvem',
      'Análises em tempo real',
      'Utilização ilimitada',
      'Histórico de apostas',
      'Suporte Individual',
      'Crie sua Estratégia (em breve)',
      'Validador de Estratégias (em breve)',
    ],
    benefitsNotIncluded: ['Estratégias Exclusivas'],
    license: 'vip',
    recurrency: 'annually',
  },
  24900: {
    name: 'Premium',
    price: 24900,
    period: 'ano',
    benefitsIncluded: [
      '100% em nuvem',
      'Análises em tempo real',
      'Utilização ilimitada',
      'Histórico de apostas',
      'Suporte Individual',
      'Crie sua Estratégia (em breve)',
      'Validador de Estratégias (em breve)',
      'Estratégias Exclusivas',
    ],
    benefitsNotIncluded: [],
    license: 'premium',
    recurrency: 'annually',
  },
}
